//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string MaAdmin { get; set; }
        public string TenAdmin { get; set; }
        public string VaiTro { get; set; }
        public string Username { get; set; }
        public string Passwords { get; set; }
    }
}
