//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderBooking
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Title { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Requests { get; set; }
        public string RoomType { get; set; }
        public Nullable<decimal> Price { get; set; }
        public System.DateTime CheckinDate { get; set; }
        public System.DateTime CheckoutDate { get; set; }
        public int RoomQuantity { get; set; }
        public System.DateTime BookingDate { get; set; }
        public string MaKhachSan { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
