//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.TourBookings = new HashSet<TourBooking>();
            this.Comboes = new HashSet<Combo>();
        }
    
        public string MaTour { get; set; }
        public string TenTour { get; set; }
        public string MoTa { get; set; }
        public System.DateTime NgayKhoiHanh { get; set; }
        public int ThoiGian { get; set; }
        public decimal Gia { get; set; }
        public string MaLoaiTour { get; set; }
        public string HinhAnh { get; set; }
        public string PhuongTien { get; set; }
        public string MaTinh { get; set; }
    
        public virtual LoaiTour LoaiTour { get; set; }
        public virtual TinhThanh TinhThanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourBooking> TourBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Combo> Comboes { get; set; }
    }
}
