//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        public string MaPhong { get; set; }
        public string MaLoai { get; set; }
        public string MaTrangThai { get; set; }
        public string MaKhachSan { get; set; }
        public string MaUser { get; set; }
        public decimal Gia { get; set; }
        public string Hinh { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
        public virtual TrangThaiPhong TrangThaiPhong { get; set; }
        public virtual User User { get; set; }
    }
}
